scripts:
  - name: 'Demo'
    path: './myscript.sh'
    parameters: 'param1 param2 "param3 multi param", param4'
    tooltip: 'Script that demonstrate how params is sent!'
  - name: 'Personnummer'
    path: 'pnr'
    parameters: '-xj 19121212-1212'
    tooltip: 'Script that call the Pnr command, directly, using params'

