scripts:
- name: 'Demo'
  path: './myscript.sh'
  parameters: 'param1 param2 "param3 multi param", param4'
  tooltip: 'Script that demonstrate how params is sent!'
- name: 'List files'
  path: 'ls'
  parameters: '-lash'
  tooltip: 'Script that call ls command directly with params -lash'
  
